version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Pointofsale
      MYSQL_USER: sonarprod_admin
      MYSQL_PASSWORD: jpfrcR3LmGdcGKKYfWsu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node_app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: sonarprod_admin
      DB_PASSWORD: jpfrcR3LmGdcGKKYfWsu
      DB_NAME: Pointofsale
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["node", "server.js"]

volumes:
  mysql_data: