name: Auto Update AWS RDS MySQL

on:
  push:
    branches:
      - main  # Run when changes are pushed to main

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Run Database Migrations
        env:
          MYSQL_HOST: ${{ secrets.AWS_DB_HOST }}
          MYSQL_USER: ${{ secrets.AWS_DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.AWS_DB_NAME }}
        run: |
          for file in migrations/*.sql; do
            echo "Applying migration: $file"
            mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" < "$file" || true
          done
